cambio en deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -8,7 +8,6 @@ on:
         required: true
         default: dev
 
-
 permissions:
   contents: read
   id-token: write
@@ -24,74 +23,90 @@ jobs:
       run:
         working-directory: terraform/envs/${{ github.event.inputs.environment }}
 
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
+        with:
+          terraform_version: 1.6.6
+
+      - name: Verify GCP secret is available
+        run: |
+          if [ -z "${{ secrets.GCP_CREDENTIALS }}" ]; then
+            echo "Secret missing!"
+            exit 1
+          else
+            echo "Secret available"
+          fi
+
+      - name: Authenticate to Google Cloud
+        uses: google-github-actions/auth@v2
+        with:
+          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
+          export_environment_variables: true
+
+      - name: Crear terraform.tfvars
+        run: |
+          cat <<EOF > terraform.tfvars
+          project     = "${{ vars.GCP_PROJECT }}"
+          region      = "${{ vars.GCP_REGION }}"
+          zone        = "${{ vars.GCP_ZONE }}"
+          EOF
+
+      - name: Terraform Init
+        run: terraform init
+
+      - name: Terraform Format
+        run: terraform fmt -check -diff -recursive
+        env:
+          TF_LOG: DEBUG
+
+      - name: Terraform Plan
+        run: terraform plan
+        env:
+          TF_LOG: DEBUG
+
+      - name: Terraform Apply
+        if: github.ref == 'refs/heads/main'
+        run: terraform apply -auto-approve
+        env:
+          TF_LOG: DEBUG
+
+      - name: Obtener IP pública
+        id: get_ip
+        run: |
+          echo "POSTGRESQL_IP=$(terraform output -raw postgresql_ip)" >> $GITHUB_ENV
+
+  ansible:
+    name: Ansible Deployment
+    runs-on: ubuntu-latest
+    needs: terraform
+    environment:
+      name: Development
+
+    defaults:
+      run:
+        working-directory: ansible
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v3
-      with:
-        terraform_version: 1.6.6
+      - name: Agregar clave SSH privada
+        run: |
+          mkdir -p ~/.ssh
+          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
 
-    - name: Verify secret is available
-      run: |
-        if [ -z "${{ secrets.GCP_CREDENTIALS }}" ]; then
-          echo "Secret missing!"
-          exit 1
-        else
-          echo "Secret available"
-        fi
+      - name: Generar inventory.ini
+        run: |
+          echo "[postgresql]" > inventory.ini
+          echo "vm-postgresql ansible_host=${POSTGRESQL_IP} ansible_user=debian ansible_ssh_private_key_file=~/.ssh/id_rsa" >> inventory.ini
 
-    - name: Authenticate to Google Cloud
-      uses: google-github-actions/auth@v2
-      with:
-        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
-        export_environment_variables: true
+      - name: Instalar Ansible
+        run: sudo apt-get update && sudo apt-get install -y ansible
 
-    - name: Crear terraform.tfvars
-      working-directory: terraform/envs/${{ github.event.inputs.environment }}
-      run: |
-        cat <<EOF > terraform.tfvars
-        project     = "${{ vars.GCP_PROJECT }}"
-        region      = "${{ vars.GCP_REGION }}"
-        zone        = "${{ vars.GCP_ZONE }}"
-        EOF
-
-    - name: Terraform Init
-      run: terraform init
-
-    - name: Terraform Format
-      run: terraform fmt -check -diff -recursive $(find . -type f -name "*.tf")
-      env:
-        TF_LOG: DEBUG
-
-    - name: Terraform Plan
-      run: terraform plan
-      env:
-        TF_LOG: DEBUG
-
-    - name: Terraform Apply
-      if: github.ref == 'refs/heads/main'
-      run: terraform apply -auto-approve
-      env:
-        TF_LOG: DEBUG
-
-    - name: Obtener IP pública
-      id: get_ip
-      run: |
-        IP=$(terraform output -raw postgresql_ip)
-        echo "POSTGRESQL_IP=$IP" >> $GITHUB_ENV
-
-    - name: Generar inventory.ini
-      working-directory: ansible
-      run: |
-        echo "[postgresql]" > inventory.ini
-        echo "vm-postgresql ansible_host=${POSTGRESQL_IP} ansible_user=debian ansible_ssh_private_key_file=~/.ssh/id_rsa" >> inventory.ini
-
-    - name: Instalar Ansible
-      run: sudo apt-get update && sudo apt-get install -y ansible
-
-    - name: Ejecutar playbook Ansible
-      working-directory: ansible
-      run: ansible-playbook -i inventory.ini playbook.yml
+      - name: Ejecutar playbook Ansible
+        run: ansible-playbook -i inventory.ini playbook.yml
